server:
  port: 9000
spring:
  application:
    name: "msvc-auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/authentication"
    username: "postgres"
    password: "1234"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
aws:
  region: "us-east-1"
  secretName: "my-secret"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
